language: python
python:
- 3.9.1
sudo: required
install:
- pip install -r requirements.txt
script:
- pytest -v
deploy:
  provider: heroku
  api_key:
    secure: nJs7+XELUL8Slnh+mQed/I7iZdon3z14n97e0QzLOpCICUwvb2GW7fu+29yfSbtGW6Zy7WXBXpDKs2gRrDGvAPsVoro7z+UdlqPqm3t4mOHqP+34MNurVdtTwlusb8argzis2Br2JCgcL60fhHSMg2aW3qtL5h0G2iXyZJok+1+IObbkrayH0uveW85izcFzJf7ef/WT2EEFY5kbR14B5/Ci6APhuwkxsvK2br0npil5utYLIzRvqijiFVe0KWu6wQ9mcKI7teR9od24GNWbGN/DQG/KV//vEVdwF1RZUjzY1vp5/w3xee8dzVrp4jw7/jxtDNDKMB6tnNO2o8caXf5AlNatctySNx+KGoZoz1m6BD508RayWbWGPzH0uABR8wRSaKOMpo2CCo8HrLZkoUcPz3DqxE0TlsfTtmndaDQou/6qP0W4g+jKxzi1F5hxI7206JwTHrJVYzmrxCZzDBEm46OThnAMY2CtdoptFZSnPD8bcr1xurEyXv8zFEYqLuoikostZV3TxalMGEnGWWj0PopAmd4IRYXy4x82SeWeXT+bYSvutodqRqquJKCTlpLkmCLDfG7aVcWoG/fljrHpxBR4AlwkniZi0cnWTrNdqYDW/ugfKp7q/NVHAlW2IeHZ2vMSEGXiMxFE5btW+v2JQ/w3xzqaU4/xhfqnjJY=
  app: the-backend
  on:
    repo: project-lolquiz/the-backend
    branch: main
  skip_cleanup: 'true'
