language: python
python:
- 3.9.1
sudo: required
install:
- pip install -r requirements.txt
script:
- pytest -v
deploy:
  provider: heroku
  api-key:
    secure: I43Mlvd0bqdJ8WUNQWtQPYyzawrGY52XkCLylYx3Fs82w5BCHqetwgm8pkJkmtFMLRoajPsvds4Y2DTo0vh3SRJN6PbaMfmBQAAfaSET6khhdr6G43O/RmrwlMKco5A//77ym5gQnyEpo6pH7ocK+OBLh/f2DkRkPDqNSVvpFPom8I/XLmT+Cf9XpqvUB8k6p7tiRdxDoUL+NAfmzmsBx/VgjglethwosfqCVz5FZNLoI0NwmeBtDqOB/xuZyi/5j+QtRKfzv0ObjrbEGFh4ahyy8E//3OdD2DX1eAPUgxW6cJhgGIjqSChs/RNro1J1vGlkNXTmm7c+9Pv2WNT9GeVwx8hD0HAdFdOGGGE9cKDRDaVcW84vlBFyjRDP5+aDRueLamQDU9PurDMep/aS0aOx9m0eo8yg/fzdS6HMSqMbKEtqw1zpKVMeazb5BBwWdjnbbOF3wlHB7HouOln349+WPuDqX49EE5W+7+NFM3WTJCFbDD0nyTkH7m+p8+1SfDye9RSfovVopFkJvYA0RhQWJ52a3+EEu9hPOpcM395dog2q8DeyKBxZAWHBLx9mAQeARTNJT0smE5QlWvrt3xXKPUG7cRd+m/LL/ctlb4GyyKtgO3yva6kr7nPi2U/IbpUqwG4AStjx+Ce7E9Wln5IiXbFDMUw6igwmsqb/CcQ=
  app: lolquizbe
  on:
    branch: main
env:
  global:
    secure: aaXfolhEvDo7dHy21AyOcq+cOzHSg/8fGqrBZ42FZTUv9SKOpnqocEWNqqdcKRd2Z/ie+JmBJOkiJLGamGmh8vusIaCGgZorXe1AjUPiiCca6k2R3SGisQfubGq7gGAt6k8lxVYeZ1yb8p5xt7f1ASWtwYNogmZGu5y18rgWTY7dVioH85KKINAMhVCs/3Avj0PEf/G51HA5V27dbfud+Ld/iDawbidruA2zKUaBOdUFCnn3bUx3whUuxDlAE2mZNZQrBOZ65T6Qhnx0L8Z+zCUVp3ET/qt4EoiBTB1x/xHJ2EbTJ6Yivm7vi1Ov8iV/T80hIRtXuk96Gp6SzvsS2A1Kv/jzvU5t04k5fQP6TWvpWvCA5gO1f00vNR0XNAmPk42KQ6WFGgiqhOuUgr2ZeD0k03r+jNRxKklFVejgEGDUcRIBE84T2h1VvtGmpQm4PvaReBQ3ZL2tGBvrQiomgAm/aQCHETR3dRkLtY5WP9x0sZ5PqF6r70b0f5JbCr9Of0xnNpt0sP2pMc3piR2tQ7YMa//dI3z65wN9Lqk8JvYoQnpRqu04MYTPsjmbErdu9FjVID2j+DeZinSuqNlwlzuL7PajsdOMEDid0RS4XXCmdQanyTOpvHn36qlZroCBn3V8Tfhq4LrOyPRpSz0AVTvQxFOQjVrg6fKppxblRT0=
