language: python
python:
- 3.9.1
sudo: required
install:
- pip install -r requirements.txt
script:
- pytest -v
deploy:
  provider: heroku
  api-key:
    secure: CS0Bw0I/KikHc0Y21WEnoe/013cdqp1oy7+TgMA13RaWxI12KAP7nqADt9WQddH+hOeuztlqq3RY/M3kPsISWWnZUug/DGwzzR8Pw55U24M6W5xG0fhBG7BrjfwBnoIYQIGY/E6IyBOg0pN9ptpkYRjFYriLHa1UAb8oiI+zi1/+pSeZLwjxPu1L2zPUV8X9wG3MtoreqHMO2AE/tgJj9lg7wdhFbUSEVyX+X69nsqeh49dbcdexSEBcY6GBbXqWOsKBnkjnPbedSpsLjWXsZ6zkuhAmwiEaCILF2TAhmfGzl4mCqAoz60byuZmcC2GwwZh6SLOC0gRMA1XyKZz/hnykGy0ENv1xM/2WEBwRRX3HZGAQ03aL2i4EHNkgZRMeJI165LMbwRxHC3IDx6b9EV8564XWXJ+Eyr3a7ed/AWj9Uy0w7piiqUNTmvg2pLGUQaqX5U7rn3nims5TDtACQWsOgg1pKnoHPJjpAmBTrY+Fc+lFU9skdNOVcGemSRgwBgjCEj4WqLZRBRfXWV/xrG6Eyd8BlK2OdWfXRX4EFMlF3DCVgI0+eW2mubjGyCmEJuFGBwIycqDv1XxEXtNiLJWHPijhNO51l/Sp0MutZn1EFdJW1uDlEAGNzmmQXhps+upc5T0HVcr36BlRn1emgdiRiMBQzOCadO/3AvRII64=
  app: lolquizbe
  on:
    branch: main
