# Linguagem Utilizada para Desenvolver a Aplicação
language: python

# Versão que a aplicação suporta.
python:
  - "3.9.1"

# Faz a instalação com Sudo, para ter privilégio de Super Usuário.
sudo: required

# Instalação de Módulos que são necessários para a Aplicação.
install:
  - pip install -r requirements.txt

# Define o script de Teste que deve rodar toda vez que o código for alterado.
script:
  - pytest -v

# Define que o processo de Deploy será na Plataforma Heroku. É necessário informar o nome da APP criada no Heroku
deploy:
  provider: heroku
  api-key:
    secure: I43Mlvd0bqdJ8WUNQWtQPYyzawrGY52XkCLylYx3Fs82w5BCHqetwgm8pkJkmtFMLRoajPsvds4Y2DTo0vh3SRJN6PbaMfmBQAAfaSET6khhdr6G43O/RmrwlMKco5A//77ym5gQnyEpo6pH7ocK+OBLh/f2DkRkPDqNSVvpFPom8I/XLmT+Cf9XpqvUB8k6p7tiRdxDoUL+NAfmzmsBx/VgjglethwosfqCVz5FZNLoI0NwmeBtDqOB/xuZyi/5j+QtRKfzv0ObjrbEGFh4ahyy8E//3OdD2DX1eAPUgxW6cJhgGIjqSChs/RNro1J1vGlkNXTmm7c+9Pv2WNT9GeVwx8hD0HAdFdOGGGE9cKDRDaVcW84vlBFyjRDP5+aDRueLamQDU9PurDMep/aS0aOx9m0eo8yg/fzdS6HMSqMbKEtqw1zpKVMeazb5BBwWdjnbbOF3wlHB7HouOln349+WPuDqX49EE5W+7+NFM3WTJCFbDD0nyTkH7m+p8+1SfDye9RSfovVopFkJvYA0RhQWJ52a3+EEu9hPOpcM395dog2q8DeyKBxZAWHBLx9mAQeARTNJT0smE5QlWvrt3xXKPUG7cRd+m/LL/ctlb4GyyKtgO3yva6kr7nPi2U/IbpUqwG4AStjx+Ce7E9Wln5IiXbFDMUw6igwmsqb/CcQ=
  app: lolquizbe
  on:
    branch: main